name: Go Test
on: [push, pull_request]
jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup system libraries
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y software-properties-common wget
        sudo add-apt-repository universe
        wget https://packages.ntop.org/apt-stable/24.04/all/apt-ntop-stable.deb
        sudo apt install ./apt-ntop-stable.deb
        sudo apt clean all
        sudo apt  update
        sudo apt install -y --no-install-recommends libpcap-dev pfring

    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Format
      if: matrix.os == 'ubuntu-latest'
      run: if [ "$(make -s fmt | wc -l)" -gt 0]; then exit 1; fi

    - name: Test
      run: make test
